export enum ReasonForVisit {
  NOT_GEO_FEASIBLE = 'NOT_GEO_FEASIBLE',
  GEO_FEASIBLE = 'GEO_FEASIBLE',
  JUST_SIGNED_IN = 'JUST_SIGNED_IN',
  NOT_ALLOWED_IN_LOCATION = 'NOT_ALLOWED_IN_LOCATION',
  NOT_ALLOWED_IN_COUNTRY = 'NOT_ALLOWED_IN_COUNTRY',
  NOT_USER = 'NOT_USER',
  USER_IS_ALLOWED = 'USER_IS_ALLOWED',
  NO_PAYMENT = 'NO_PAYMENT',
  ERROR = 'ERROR',
}
