version: '3'

services:
  base-cloud:
    container_name: base-cloud
    build:
      context: .
      dockerfile: ./apps/base-cloud/Dockerfile
      args:
        - VITE_APP_NAME=${VITE_APP_NAME}
    restart: always
    ports:
      - 3030:3030
