name: Preview Base-App

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3

      - name: 🏗 Setup monorepo
        uses: ./.github/actions/setup-monorepo
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}

      - name: 👷 Build packages
        run: pnpm run -w build

      - name: 🚀 Publish preview
        working-directory: apps/base-app
        run: expo publish --release-channel=pr-${{ github.event.number }}

      - name: 💬 Comment preview
        uses: expo/expo-github-action/preview-comment@v7
        with:
          project: apps/base-app
          channel: pr-${{ github.event.number }}
